### PR TITLE
Pass provider credentials as environment variables

### LINKED ISSUE #99: Logs and events may contain provider credentials
### What happened?

Trying to create an elasticache cluster and it failed for some reason I am still debugging, but realized another problem which is terraform logs and event on cr contains `access_key/secret_key`:

See the following (intentionally replaced with `REDACTED`): 

```
  conditions:
  - lastTransitionTime: "2021-10-08T17:02:05Z"
    message: |-
      observe failed: cannot run refresh: cannot refresh: {"@level":"info","@message":"Terraform 1.0.4","@module":"terraform.ui","@timestamp":"2021-10-08T20:02:04.398569+03:00","terraform":"1.0.4","type":"version","ui":"0.1.0"}
      {"@level":"info","@message":"\nInterrupt received.\nPlease wait for Terraform to exit or data loss may occur.\nGracefully shutting down...\n","@module":"terraform.ui","@timestamp":"2021-10-08T20:02:05.046946+03:00","type":"log"}
      {"@level":"error","@message":"Error: Missing required argument","@module":"terraform.ui","@timestamp":"2021-10-08T20:02:05.943625+03:00","diagnostic":{"severity":"error","summary":"Missing required argument","detail":"The argument \"cluster_id\" is required, but no definition was found.","range":{"filename":"main.tf.json","start":{"line":1,"column":859,"byte":858},"end":{"line":1,"column":860,"byte":859}},"snippet":{"context":"resource.aws_elasticache_cluster.sample-cluster","code":"{\"provider\":{\"tf-provider\":{\"access_key\":\"REDACTED\",\"region\":\"us-east-1\",\"secret_key\":\"REDACTED\",\"token\":\"\"}},\"resource\":{\"aws_elasticache_cluster\":{\"sample-cluster\":{\"apply_immediately\":null,\"availability_zone\":null,\"az_mode\":null,\"cluster_identifier\":\"sample-cluster\",\"engine\":\"memcached\",\"engine_version\":null,\"final_snapshot_identifier\":null,\"lifecycle\":{\"prevent_destroy\":true},\"maintenance_window\":null,\"node_type\":\"cache.t2.micro\",\"notification_topic_arn\":null,\"num_cache_nodes\":1,\"parameter_group_name\":\"default.memcached1.4\",\"port\":11211,\"preferred_availability_zones\":null,\"replication_group_id\":null,\"security_group_ids\":null,\"security_group_names\":null,\"snapshot_arns\":null,\"snapshot_name\":null,\"snapshot_retention_limit\":null,\"snapshot_window\":null,\"subnet_group_name\":null,\"tags\":null,\"tags_all\":null}}},\"terraform\":{\"required_providers\":{\"tf-provider\":{\"source\":\"hashicorp/aws\",\"version\":\"3.56.0\"}}}}","start_line":1,"highlight_start_offset":858,"highlight_end_offset":859,"values":[]}},"type":"diagnostic"}
```

### How can we reproduce it?

Trigger a problem and observe terraform logs.

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Fixes #99

This PR proposes a change in which we pass provider specific credentials as environment variables.

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Tested with provider-tf-azure.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/terraform/store.go [hunk 1]
```diff
@@ -49,9 +49,10 @@ type ProviderConfiguration map[string]interface{}
 // Setup holds values for the Terraform version and setup
 // requirements and configuration body
 type Setup struct {
-	Version       string
-	Requirement   ProviderRequirement
-	Configuration ProviderConfiguration
+	Version        string
+	Requirement    ProviderRequirement
+	Configuration  ProviderConfiguration
+	CredentialsEnv []string
```
Comment (turkenh) [inline pkg/terraform/store.go:55]: I felt a bit confused about having this as a []string rather than some map[string]string keeping key-value pairs but looks like this is already the type how cmd.Env expects the env vars. So, looking good.

File: pkg/terraform/workspace.go [hunk 2]
```diff
@@ -132,6 +134,7 @@ func (w *Workspace) Apply(ctx context.Context) (ApplyResult, error) {
 	}
 	cmd := exec.CommandContext(ctx, "terraform", "apply", "-auto-approve", "-input=false", "-lock=false", "-json")
 	cmd.Dir = w.dir
+	w.setChildEnv(cmd)
```
Comment (muvaf) [inline pkg/terraform/workspace.go:137]: nitpick

Quoting from comments of `Env` field:
> 	// Env specifies the environment of the process.
	// Each entry is of the form "key=value".
	// If Env is nil, the new process uses the current process's
	// environment.

Would it be more clear if we do the operation here?
```suggestion
	cmd = append(os.Environ(), w.credentialsEnv...)
```

File: pkg/terraform/workspace.go [hunk 3]
```diff
@@ -71,8 +71,9 @@ type Workspace struct {
 	// LastOperation contains information about the last operation performed.
 	LastOperation *Operation
 
-	dir    string
-	logger logging.Logger
+	dir            string
+	credentialsEnv []string
```
Comment (muvaf) [inline pkg/terraform/workspace.go:75]: nitpick
```suggestion
	env []string
```

File: pkg/terraform/workspace.go (hunk 2 above)
Comment (ulucinar) [reply pkg/terraform/workspace.go]: Moved cmd.Dir sets also to that function.
